# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10m3lLnrWAA4UkO_3EqL-udo2cMS5M11h
"""

# streamlit_app.py
import streamlit as st
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

st.title("Clustering Tren Harian COVID-19")

uploaded_file = st.file_uploader("Upload CSV file", type="csv")
if uploaded_file:
    df = pd.read_csv(uploaded_file)
    data = df[['New Cases', 'New Deaths', 'New Recovered', 'Active Cases']].dropna()
    scaler = StandardScaler()
    data_scaled = scaler.fit_transform(data)

    kmeans = KMeans(n_clusters=3)
    df['Cluster'] = kmeans.fit_predict(data_scaled)

    st.subheader("Visualisasi Klaster")
    fig, ax = plt.subplots()
    sns.scatterplot(data=df, x='New Cases', y='Active Cases', hue='Cluster', ax=ax)
    st.pyplot(fig)

    st.subheader("Statistik Klaster")
    st.dataframe(df.groupby('Cluster')[['New Cases', 'New Deaths', 'New Recovered', 'Active Cases']].mean().round(2))