# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10m3lLnrWAA4UkO_3EqL-udo2cMS5M11h
"""

# streamlit_app.py
import streamlit as st
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

st.title("Clustering Tren Harian COVID-19 di Indonesia")

uploaded_file = st.file_uploader("Upload file CSV dengan data COVID-19", type="csv")

if uploaded_file:
    df = pd.read_csv(uploaded_file)

    # Pilih kolom-kolom numerik untuk clustering (versi bahasa Indonesia)
    data = df[['jumlah_positif', 'jumlah_meninggal', 'jumlah_sembuh', 'jumlah_dirawat']].dropna()

    # Standarisasi data
    scaler = StandardScaler()
    data_scaled = scaler.fit_transform(data)

    # K-Means Clustering
    kmeans = KMeans(n_clusters=3, random_state=42)
    df.loc[data.index, 'Cluster'] = kmeans.fit_predict(data_scaled)

    # Visualisasi hasil clustering
    st.subheader("Visualisasi Klaster")
    fig, ax = plt.subplots()
    sns.scatterplot(data=df.loc[data.index], x='jumlah_positif', y='jumlah_dirawat', hue='Cluster', palette='Set1', ax=ax)
    plt.xlabel("Jumlah Positif Harian")
    plt.ylabel("Jumlah Dirawat Aktif")
    plt.title("Visualisasi Klaster Berdasarkan Kasus Baru dan Kasus Aktif")
    st.pyplot(fig)

    # Statistik ringkasan per klaster
    st.subheader("Statistik Rata-rata Tiap Klaster")
    st.dataframe(df.groupby('Cluster')[['jumlah_positif', 'jumlah_meninggal', 'jumlah_sembuh', 'jumlah_dirawat']].mean().round(2))
